# /workspaces/WazeLog/routing/osrm_local/docker-compose.yml

services:
  osrm-backend-local: # Renomeado para local
    image: osrm/osrm-backend:latest
    container_name: osrm_backend_local # Renomeado para local
    restart: unless-stopped
    ports:
      - "5000:5000" # Porta para o servidor local
    volumes:
      - ./data:/data
    # Comando para usar o arquivo .osrm da sua região principal (ex: sao-paulo)
    command: osrm-routed --algorithm mld /data/sao-paulo-latest.osrm # Usando arquivo menor para menos RAM

  osrm-preprocess-local: # Renomeado para local
    image: osrm/osrm-backend:latest
    container_name: osrm_preprocess_local # Renomeado para local
    volumes:
      - ./data:/data
    # Sequência de comandos para processar o arquivo .osm.pbf da sua região principal (agora usando sao-paulo)
    command: >
      bash -c "\
      if [ ! -f /data/sao-paulo-latest.osm.pbf ]; then \
        echo '--- ERRO: Arquivo /data/sao-paulo-latest.osm.pbf não encontrado. Faça o download do Geofabrik e coloque na pasta ./data ---'; \
        exit 1; \
      fi; \
      echo '--- Iniciando pré-processamento OSRM para Local ---'; \
      osrm-extract -p /opt/car.lua /data/sao-paulo-latest.osm.pbf; \
      echo '--- Extração concluída (Local) ---'; \
      osrm-partition /data/sao-paulo-latest.osrm; \
      echo '--- Particionamento concluído (Local) ---'; \
      osrm-customize /data/sao-paulo-latest.osrm; \
      echo '--- Customização concluída (Local) ---'; \
      echo '--- Pré-processamento OSRM Local concluído com sucesso! ---'"